### ISSUE TITLE
Convert to monorepo

### ISSUE THREAD

**Issue by deepanchal** [ArroyoDev-LLC/Big3D#33]
## Description

Convert repo to pnpm monorepo.

## Screenshots

N/A

## Tasks

- [x] convert to monorepo with pnpm
- [x] update paths and code
- [x] fix errors with migration
